CREATE TABLE TBL_REPLY(
	REPLY_NUMBER NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000),
	REPLY_WRITER VARCHAR2(500),
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	BOARD_NUMBER NUMBER,
	CONSTRAINT FK_REPLY FOREIGN KEY(BOARD_NUMBER)
	REFERENCES TBL_BOARD(BOARD_NUMBER) ON DELETE CASCADE
);

SELECT * FROM TBL_REPLY;